config/routes.rb
Rails.application.routes.draw do

  resources :send_mails do
    collection do
      get :draft_mail
     end
  end
   root 'send_mails#index'

end

app/models/file_attachment.rb
class FileAttachment < ActiveRecord::Base
  attr_accessible :file
   mount_uploader :file, FileUploader
  belongs_to :send_mail
end

app/models/send_mail.rb
class SendMail < ActiveRecord::Base
  attr_accessible :to, :subject, :body, :file_attachments_attributes
  
  validates :to, :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  has_many :file_attachments, :dependent => :destroy
  accepts_nested_attributes_for :file_attachments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/send_mails_controller.rb
class SendMailsController < InheritedResources::Base
  def create    
    @send_mail = SendMail.new(params[:send_mail])    
    @send_mail.status = true if params[:submit] == "Send"
    if @send_mail.save && params[:submit] == "Send"
      UserMailer.compose(@send_mail).deliver
      redirect_to send_mails_path
    elsif @send_mail.save && params[:submit] == "Save As Draft"      
      redirect_to draft_mail_send_mails_path
    else
      render 'new'
    end
  end
  
  def draft_mail
    @send_mails = SendMail.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/send_mails_helper.rb
module SendMailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PmgMail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/send_mails/_add_file_attachment.html.erb
<table>
  <tr>
    <td>
      <%= f.input :file,  :as => :file %>
    </td>
  </tr>
</table>

app/views/send_mails/_form.html.erb
<%= semantic_form_for @send_mail do |f| %>
  <%= f.label 'To:'%>
  <%= f.input :to, :label => false %>
  <%= f.label 'Subject:'%>
  <%= f.input :subject, :label => false %>
  <%= f.label 'Body:'%>
  <%= f.input :body,       :input_html => { :rows => 10, :cols => 20 }, :label => false%>
  <%= f.inputs do %>
	  <div>
		  <%= f.semantic_fields_for :file_attachments do |ff|%>
		    <%= render :partial => "add_file_attachment", :locals=>{:f => ff} %>
		  <% end %>
		  <tr id="add">
		    <td colspan='3'>
		      <%= link_to_add_association 'Attach Files', f, :file_attachments, :partial => "add_file_attachment" -%>
		    </td>
		  </tr>
	  </div>
  <% end %>
  <br>
  <%= f.submit 'Send' , :name => 'submit'%>
  <%= f.submit 'Save As Draft' , :name => 'submit'%>
  
<% end %>

app/views/send_mails/draft_mail.html.erb
<div class="col-md-10">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>To</th>
      <th>Subject</th>
    </tr> 
  </thead>
  <tbody>
    <% @send_mails.each do |send_mail| %>
    <% if send_mail.status == false %>
      <tr>
        <td class="col-md-4"><%= link_to send_mail.to, edit_send_mail_path(send_mail) %></td>
        <td><%= link_to send_mail.subject, edit_send_mail_path(send_mail) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>  
</div>
</div>

app/views/send_mails/edit.html.erb
<%= render 'form'%>

app/views/send_mails/index.html.erb
<div class="mail_index">
  <div class="col-md-2">
    <%= link_to "Compose", new_send_mail_path, :class=>"btn btn-danger" %>
    <%= link_to "Draft", draft_mail_send_mails_path, :class=>"btn btn-primary" %>
  </div>
<div class="col-md-10">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>To</th>
      <th>Subject</th>
    </tr> 
  </thead>
  <tbody>
    <% @send_mails.each do |send_mail| %>
    <% if send_mail.status == true %>
      <tr>
        <td class="col-md-4"><%= link_to send_mail.to, send_mail %></td>
        <td><%= link_to send_mail.subject, send_mail %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>  
</div>
</div>

app/views/send_mails/new.html.erb
<%= render 'form'%>

app/views/send_mails/show.html.erb
<ul class="mail_inbox table-bordered col-md-offset-3 col-md-6">
  <li class="mail_subject col-md-12"><%= @send_mail.subject%></li>
<li class="mail_to col-md-12"><%= @send_mail.to%></li>
<li class="mail_body col-md-12 "><%= @send_mail.body%></li>
</ul>